### ISSUE TITLE
Image previews in timeline are extremely short`

### ISSUE THREAD

**Issue by ashyon** [dangeredwolf/ModernDeck#67]
![screenshot from 2016-06-05 08-37-12](https://cloud.githubusercontent.com/assets/9281956/15805444/cef1e1ca-2af8-11e6-990d-9800adf250fa.png)

**Comment by ciolt** [comment]
There can be about only three changes to this: expand an image to the full width, stretch them to a certain height, or add a button to show the images in the media popup.

**Comment by dangeredwolf** [comment]
Fixed./

**Comment by ashyon** [comment]
Still not fixed. Problem is with media-size-* css selector, all images in timeline are media-size-small which is very short but wide. Solution: add option for image preview size.
![screenshot from 2016-06-10 19-32-28](https://cloud.githubusercontent.com/assets/9281956/15981341/1966c368-2f42-11e6-898f-8eb34a6b9a50.png)
